version: '3.7'

services:
  web_server:
    container_name: web_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - logging-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html
      - ./json_log.conf:/etc/nginx/conf.d/json_log.conf
    ports:
      - 80:80
      - 443:443
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: httpd.access
    depends_on:
      - fluentd

  fluentd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluentd
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - logging-net

networks:
  logging-net:
    external: true
