version: '3.7'

services:
  web_server:
    container_name: web_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - logging-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html
      # - ./json_log.conf:/etc/nginx/conf.d/json_log.conf
    ports:
      - 81:80
      - 443:443


networks:
  logging-net:
    external: true

