version: '3.7'

services:
  revproxy:
    container_name: web_server
    # build:
    # context: .
    # dockerfile: Dockerfile
    image: nginx-fluentd
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
  redis_network:
    external: true
